#!/usr/bin/env bash
# web debugging to make Nginx listen on port 80
new_string="listen 80 default_server;\n"
second_string="listen [::]:80 default_server ipv6only=on;\n"
sudo sed -i "21i $new_string" ~/../etc/nginx/sites-available/default
sudo sed -i "22i $second_string" ~/../etc/nginx/sites-available/default
sudo service nginx restart
