#!/usr/bin/env bash
# transfers a file from client to server
# $1: path to the file to be transfered
# $2: the ip of the server we want to transfer the file to
# $3 the username scp connects with
# $4: the path to the ssh private key that scp uses
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no "$4" "$1" "$3@$2":~/
fi
