#!/usr/bin/env bash
# configures nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo echo "Holberton School" > /usr/share/nginx/html/index.html
sudo service nginx restart
