#!/usr/bin/env bash
# condifigures /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
new_string="location /redirect_me/ {\nrewrite ^(.*) $https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; \\
n}"
sudo sed -i "30i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
error_string=" error_page 404 /custom_404.html;\nlocation = /custom_404.html { \nroot /usr/share/nginx/html;\\
ninternal;\n}"
sudo sed -i "27i $error_string"  /etc/nginx/sites-available/default
sudo service nginx restart
