#!/usr/bin/env bash
# change user to nginx, have it listen on all active IPs
sudo pkill -f apache2
sudo chmod 777 /etc/nginx/nginx.conf
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server/8080 default_server/g" /etc/nginx/sites-available/default
sudo service nginx restart
